### ISSUE TITLE
Installation fails for Enterprise

### ISSUE THREAD

**Issue by jean** [EWSoftware/VSSpellChecker#131]
Renaming the folder from `Enterprise` to `Professional` fixed the installation.

```
8/22/2017 2:54:03 PM - Found installed product - Visual Studio Professional 2017 (2)
8/22/2017 2:54:03 PM - System.IO.FileNotFoundException: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.exe
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at VSIXInstaller.SupportedVSSKU.get_VersionWithBuildRevisionInfo()
   at VSIXInstaller.App.IsValidSKUForExtension(SupportedVSSKU supportedSKU, IExtension extension, List`1 validSKUs)
   at VSIXInstaller.App.ShouldAddSkuToValidSkuList(SupportedVSSKU sku, IInstallableExtension extension, List`1 validSKUs)
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

(Logging this for @LegendORC )

**Comment by EWSoftware** [comment]
Sounds like a VSIX installer issue.  The manifest is set to install in the Community edition or above.  I'm not aware of anyone else with this issue.
