### ISSUE TITLE
Can't install on 2017 latest

### ISSUE THREAD

**Issue by sadjadbp** [EWSoftware/VSSpellChecker#183]
Installed 15.8.5 and 15.9.0 Preview 3 and I cannot install the extension, here is log

9/26/2018 4:23:52 PM - Searching for applicable products...
9/26/2018 4:23:52 PM - Found installed product - Global Location
9/26/2018 4:23:52 PM - Found installed product - ssms
9/26/2018 4:23:52 PM - Found installed product - Visual Studio Enterprise 2017
9/26/2018 4:23:52 PM - Found installed product - Visual Studio Enterprise 2017 Int Preview
9/26/2018 4:23:52 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by EWSoftware** [comment]
15.8.5 should allow it to install.  The current release doesn't know about the 15.9 preview so it won't install on that version yet.  The next update will allow for that.

**Comment by sadjadbp** [comment]
I have them all and installer failed to install on all of them!

**Comment by EWSoftware** [comment]
Like I said, it won't install in 15.9.  However, I downloaded and tested it with 15.8.5 and it installs.  I don't know why it won't on yours.  I'd suggest trying it on another PC without the Preview to see if perhaps it's messing it up somehow.
