### ISSUE TITLE
IndexOutOfRangeException on #include directive

### ISSUE THREAD

**Issue by wansor** [EWSoftware/VSSpellChecker#199]
In Visual Studio 2019 I get an IndexOutOfRangeException when I try to enter an #include directive into a C++ file. It happens after typing "#include" just after the final 'e'. Interestingly, this only happens for the first #include. If I ignore the message, everything seems to be working as expected.

Here's the stack trace from VS's log file:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
 at VisualStudio.SpellChecker.Tagging.CSharp.CSharpCommentTextTagger.ScanDefault(LineProgress p)
 at VisualStudio.SpellChecker.Tagging.CSharp.CSharpCommentTextTagger.ScanLine(State state, ITextSnapshotLine line, List`1 naturalTextSpans)
 at VisualStudio.SpellChecker.Tagging.CSharp.CSharpCommentTextTagger.RescanLines(ITextSnapshot snapshot, Int32 startLine, Int32 lastDirtyLine)
 at VisualStudio.SpellChecker.Tagging.CSharp.CSharpCommentTextTagger.OnTextBufferChanged(Object sender, TextContentChangedEventArgs e)
 at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)
 --- End of stack trace from previous location where exception was thrown ---
 at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by EWSoftware** [comment]
I've fixed it.  A new release will be available shortly.
