### ISSUE TITLE
Crash Hovering over Add to Ignore Words File

### ISSUE THREAD

**Issue by davidbsanderson** [EWSoftware/VSSpellChecker#209]
In version 2020.3.28.0, Visual Studio Professional 2017 Version 15.9.20 is crashing whenever hovering over the "Add to Ignore Words File" option in the spell checker popup.

An error is presented in Visual Studio which is recorded in the event log.

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
   at System.Windows.Controls.ItemCollection.GetItemAt(Int32)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbMenuItem.FocusAndExpandSubmenu()
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbMenuItem+<InitializeNonFlavoredAsync>d__18.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbMenuItem+<InitializeAsync>d__17.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulb+<OnMenuItemGotKeyboardFocus>d__59.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by EWSoftware** [comment]
I'm not able to duplicate this with 15.9.21.  Are there multiple ignored words files or just the global one?  Are there any particular steps you take to reproduce the issue?

**Comment by davidbsanderson** [comment]
I played around with it some more and was able to resolve it.

When the extension was updated, it did not create an IgnoredWords.dic file in \AppData\Local\EWSoftware\Visual Studio Spell Checker. I went into Configuration Settings > Ignored Words and clicked Edit on the Ignored Words File, which asked if I wanted to create the file since it didn't exist. After doing so, the popup now displays "Add to Ignored Words File Global" and does not crash upon hover. Before, it must have thought I had multiple files because it was attempting to display a dropdown upon hover instead of saying "Global".

**Comment by EWSoftware** [comment]
Thanks.  I'll check on that as it shouldn't need to exist.

**Comment by srupprecht1** [comment]
I had the same issue in VS2019 and @davidbsanderson solution solves this for me.

**Comment by PropelledDog** [comment]
Hey @srupprecht1 
I am using VS2019 too, but I am not able to find the configuration options for this extension. @davidbsanderson stated the following:

> "_I went into Configuration Settings > Ignored Words and clicked Edit on the Ignored Words File [...]_"

Where are the configuration settings? Was @davidbsanderson talking about the "Properties" when you right click on a project solution? I don't see any such configuration options there.

Where is this "Ignored Words" setting in Visual Studio 2019?

**Comment by EWSoftware** [comment]
Go to the Tools menu, select Spell Checker, and then [Edit Global Configuration](http://ewsoftware.github.io/VSSpellChecker/html/fb81c214-0fe0-4d62-a172-d7928d5b91d5.htm).
