### ISSUE TITLE
Spell checker crash

### ISSUE THREAD

**Issue by djmarcus1** [EWSoftware/VSSpellChecker#212]
I got this crash of the spell checker:

System.NullReferenceException : Object reference not set to an instance of an object.
   at IntelliSenseExtender.Extensions.SemanticModelExtensions.GetTupleTypeFromReturnValue(ITypeSymbol returnTypeSymbol,Int32 elementIndex)
   at IntelliSenseExtender.Extensions.SemanticModelExtensions.GetTypeSymbol(SemanticModel semanticModel,SyntaxToken currentToken)
   at async IntelliSenseExtender.Context.SyntaxContext.CreateAsync(<Unknown Parameters>)
   at async IntelliSenseExtender.IntelliSense.Providers.AggregateTypeCompletionProvider.ProvideCompletionsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetContextAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.ComputeNonEmptyCompletionContextsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetCompletionsWithAvailabilityOfExpandedItemsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetCompletionsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.CreateSpellCheckCodeIssueAsync[TSimpleName](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.CheckNodeAsync[TSimpleName](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.RegisterCodeFixesAsync[TSimpleName](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)

**Comment by EWSoftware** [comment]
That's not mine.  It looks like it's part of the Microsoft code analysis spell checking.  I don't currently have a code analysis spell checker, just an editor extension.  Mine will make use of the code analysis dictionaries but only for spell checking the strings and comments as performed by the editor extension.  It doesn't integrate with code analysis at all.

**Comment by djmarcus1** [comment]
I'll report it to Microsoft.. thanks
