### ISSUE TITLE
Failed to install on VS 2019 Pro

### ISSUE THREAD

**Issue by maruashok** [EWSoftware/VSSpellChecker#225]
19-Dec-2020 04:11:28 PM - Microsoft VSIX Installer
19-Dec-2020 04:11:28 PM - -------------------------------------------
19-Dec-2020 04:11:28 PM - vsixinstaller.exe version:
19-Dec-2020 04:11:28 PM - 16.8.3038
19-Dec-2020 04:11:28 PM - -------------------------------------------
19-Dec-2020 04:11:28 PM - Command line parameters:
19-Dec-2020 04:11:28 PM - C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\vsixinstaller.exe,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\devenv.exe,/skuName:Pro,/skuVersion:16.8.30717.126,/appidname:Microsoft Visual Studio Professional 2019,/culture:en-US,/noep,C:\Windows\TEMP\VSIXdvzrk4dn.vsix
19-Dec-2020 04:11:28 PM - -------------------------------------------
19-Dec-2020 04:11:28 PM - Microsoft VSIX Installer
19-Dec-2020 04:11:28 PM - -------------------------------------------
19-Dec-2020 04:11:29 PM - Initializing Install...
19-Dec-2020 04:11:29 PM - Extension Details...
19-Dec-2020 04:11:29 PM - 	Identifier         : 43EA967E-0DE2-4136-8E52-C6DCFB5C2748
19-Dec-2020 04:11:29 PM - 	Name               : Visual Studio Spell Checker (VS2017 and Later)
19-Dec-2020 04:11:29 PM - 	Author             : EWSoftware
19-Dec-2020 04:11:29 PM - 	Version            : 2020.8.24.0
19-Dec-2020 04:11:29 PM - 	Description        : An editor extension that checks the spelling of comments, strings, and plain text as you type or interactively with a tool window.  It can also spell check an entire solution, project, or selected items.  Options are available to define multiple languages to spell check against, define ignored words, control how elements and attributes in XML and MAML files are spell checked, and much more.
19-Dec-2020 04:11:29 PM - 	Locale             : en-US
19-Dec-2020 04:11:29 PM - 	MoreInfoURL        : https://ewsoftware.github.io/VSSpellChecker
19-Dec-2020 04:11:29 PM - 	InstalledByMSI     : False
19-Dec-2020 04:11:29 PM - 	SupportedFrameworkVersionRange : [4.6,)
19-Dec-2020 04:11:29 PM - 
19-Dec-2020 04:11:29 PM - 	SignatureState     : Unsigned
19-Dec-2020 04:11:29 PM - 	Supported Products : 
19-Dec-2020 04:11:29 PM - 		Microsoft.VisualStudio.Community
19-Dec-2020 04:11:29 PM - 			Version : [15.0.27130.0,17.0)
19-Dec-2020 04:11:29 PM - 
19-Dec-2020 04:11:29 PM - 	References         : 
19-Dec-2020 04:11:29 PM - 	Prerequisites      : 
19-Dec-2020 04:11:29 PM - 		-------------------------------------------------------
19-Dec-2020 04:11:29 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
19-Dec-2020 04:11:29 PM - 		Name         : Visual Studio core editor
19-Dec-2020 04:11:29 PM - 		Version      : [15.0,)
19-Dec-2020 04:11:29 PM - 
19-Dec-2020 04:11:29 PM - Signature Details...
19-Dec-2020 04:11:29 PM - 	Extension is not signed.
19-Dec-2020 04:11:29 PM - 
19-Dec-2020 04:11:29 PM - System.Runtime.InteropServices.COMException (0x80040154): Retrieving the COM class factory for component with CLSID {177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at VSIXInstaller.LocationBasedSKU..ctor(String appidInstallPath, String appidName, Version vsVersion, String edition, String rootSuffix)
   at VSIXInstaller.LocationBasedSKU..ctor(String appidInstallPath, String appidName, Version vsVersion, String edition, String rootSuffix, IntPtr alternateUserToken)
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.ComputeInstallableExtensions(IStateData stateData, Boolean isRepairSupported, Boolean isExtensionPack, IDictionary`2 skuDataMapping, IList`1 installableExtensionsPaths)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by maruashok** [comment]
Just repaired VS
