### ISSUE TITLE
Null reference `_dictionary` can be null @ SpellingTagger.cs:685

### ISSUE THREAD

**Issue by ariccio** [EWSoftware/VSSpellChecker#31]
0. Open a C++ project
1. (in a comment) Add a word, that VSSpellChecker thinks is misspelled, to the dictionary
2. Switch to a different (already open) tab (another file).
3. Close the first file, via the `x` in the tab-bar (document well?)

![dictionarynullreference](https://cloud.githubusercontent.com/assets/2142308/7829078/e9379978-040a-11e5-8ed9-7165814001b3.PNG)

**Comment by ariccio** [comment]
Exception detail:

```
System.NullReferenceException occurred
  _HResult=-2147467261
  _message=Object reference not set to an instance of an object.
  HResult=-2147467261
  IsTransient=false
  Message=Object reference not set to an instance of an object.
  Source=VisualStudio.SpellChecker
  StackTrace:
       at VisualStudio.SpellChecker.SpellingTagger.<GetMisspellingsInSpans>d__29.MoveNext() in c:\Users\Alexander Riccio\Documents\GitHub\VSSpellChecker\Source\VSSpellChecker\SpellingTagger.cs:line 685
  InnerException: 

```

**Comment by ariccio** [comment]
Output window text:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at VisualStudio.SpellChecker.SpellingTagger.<GetMisspellingsInSpans>d__29.MoveNext() in c:\Users\Alexander Riccio\Documents\GitHub\VSSpellChecker\Source\VSSpellChecker\SpellingTagger.cs:line 685
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at VisualStudio.SpellChecker.SpellingTagger.CheckSpellings(IEnumerable`1 dirtySpans) in c:\Users\Alexander Riccio\Documents\GitHub\VSSpellChecker\Source\VSSpellChecker\SpellingTagger.cs:line 592
   at VisualStudio.SpellChecker.SpellingTagger.GuardedCheckSpellings(Object dirtySpansObject) in c:\Users\Alexander Riccio\Documents\GitHub\VSSpellChecker\Source\VSSpellChecker\SpellingTagger.cs:line 555
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----
Exception!Object reference not set to an instance of an object.
---- Assert Long Message ----

   at VisualStudio.SpellChecker.SpellingTagger.GuardedCheckSpellings(Object dirtySpansObject) in c:\Users\Alexander Riccio\Documents\GitHub\VSSpellChecker\Source\VSSpellChecker\SpellingTagger.cs:line 564
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

```

**Comment by EWSoftware** [comment]
I haven't been able to duplicate this issue with the steps given.  However, since it appears to be a threading issue, I can probably take steps to prevent it form happening.

**Comment by ariccio** [comment]
Fair enough.
